# Generated by Django 4.2.6 on 2023-10-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieorder',
            old_name='perchased_at',
            new_name='purchased_at',
        ),
    ]
